name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  Coverage-Report:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python for branch
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies for branch
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Create .env file
        run: |
          echo "OPENWEATHER_API_KEY=some_key" >> .env
      - name: Run tests with coverage
        run: |
          poetry run pytest --cov --cov-report=lcov:${{ github.head_ref }}-coverage.lcov
      - name: Get list of artifacts
        id: main_coverage_artifact
        run: |
          response=$(gh api repos/${{ github.repository }}/actions/artifacts?name=main-coverage.lcov)
          freshest_artifact=$(echo "$response" | jq -r '.artifacts | sort_by(.created_at) | last')
          workflow_run_id=$(echo "$freshest_artifact" | jq -r '.workflow_run.id')
          echo "run_id=$workflow_run_id" >> $GITHUB_OUTPUT
      - name: check run_id
        run: |
          echo "run_id=${{ steps.main_coverage_artifact.outputs.run_id }}"
      - name: Download main report
        uses: actions/download-artifact@v4
        with:
          name: main-coverage.lcov
          run-id: ${{ steps.main_coverage_artifact.outputs.run_id }}
          github-token: ${{ env.GH_TOKEN }}
      - name: Add comment with coverage report
        uses: romeovs/lcov-reporter-action@v0.3.1
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ github.token }}
          lcov-file: coverage.lcov
          lcov-base: main-coverage.lcov
          delete-old-comments: true
      - name: Check and delete existing reports for the PR
        id: pr_coverage_artifact
        run: |
          response=$(gh api repos/${{ github.repository }}/actions/artifacts?name=${{ github.head_ref }}-coverage.lcov)
          total_count=$(echo "$response" | jq -r '.total_count')
          if [ "$total_count" -gt 0 ]; then
            echo "Found $total_count artifacts. Deleting..."
            echo "$response" | jq -c '.artifacts[]' | while read artifact; do
              artifact_id=$(echo "$artifact" | jq -r '.id')
              gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$artifact_id
            done
          else
            echo "No artifacts found for deletion."
          fi
      - name: Upload PR's coverage report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.head_ref }}-coverage.lcov
          path: ${{ github.head_ref }}-coverage.lcov
          overwrite: true

